### ISSUE TITLE
RealChat UI Request

### ISSUE THREAD

**Issue by ryankimjh00** [Team-Discipline/Xlack-Frontend#10]
@ryd10227  
Real Chat backend code structure is roughly built. plz check my code in the `Team-Discipline/Xlack-Backend/Feature/RealChat` branch.
The file path is `Xlask-Backend/app/RealChat/realchat.py` Check TODO here.
This is Commit Hash(SHA) `65999cdd42ae9df1440dd9e05a770d7ba1d37e75`

**Comment by kreimben** [comment]
Please issue pull-request to backend repository if branch is almost ready.
By any chance I will test notification directly to my phone.

**Comment by ryankimjh00** [comment]
OK👌
