### ISSUE TITLE
[f] 추가 작업

### ISSUE THREAD

**Issue by ryankimjh00** [Team-Discipline/Xlack-Frontend#106]
- [x] localhost로 하드코딩 돼있는 부분 우리 xlack url로 변경하기(개발모드/배포모드) 나눠서
- [x] ~~Workspace hover 하면 흰색테두리 쳐지는것 처럼 선택한 ws 유지되게~~
- [x] Chat 100개 array로 저장해서 채널별로 다 저장해놓기
- [ ] Pagination(무한스크롤? 화살표 버튼?)
- [x] 알림 연결 변경된 사항에 맞춰서 수정
- [x] 채팅에서 처음 채팅 치면 이름이 한번만 안나오는 버그 수정
- [x] 알림 하나에 5번오는거 수정
- [ ] 작업 진행중일때 로딩표시 띄워주기
- [x] 파일 전송되면 채팅으로 띄워주기
   - [x] 파일 다운로드 기능 만들기 
- [x] 채팅 저장방식 업데이트로 인한 History improve
- [x] Bookmark toggle 문구 변경해주기
- [x] Bookmark 문구 업데이트 적용해주기
- [x] 내가 채팅방 A에 있을경우 A에 오는 메세지는 실시간으로 업데이트 안됨(알림만 옴)
    - 알림 웹소켓과 충돌로 챗 웹소켓이 순간 끊기는걸로 추정중(원인 파악 필요)
- [x] 리액션 버그잡기(현재 filter에 가끔 버그, 화면갱신 버그)
- [x] workspace 초대기능
- [x] notification pop up 클릭하면 해당 채널로 이동
- [x] reaction 저장

----
## UI retouch
- [x] chat ui 
- [x] workspace 클릭시 모달창 뜨는거 삭제
- [x] status profile menu에 뜨게

**Comment by ss35789** [comment]
5번째 꺼 아마 연결 작업 끝나기 전에 채팅쳐서 그런 걸 수도 있음 
작업 진행중일 때 로딩 표시해주기 작업도 추가

**Comment by ryankimjh00** [comment]
> 5번째 꺼 아마 연결 작업 끝나기 전에 채팅쳐서 그런 걸 수도 있음 
> 작업 진행중일 때 로딩 표시해주기 작업도 추가
> @ryankimjh00 

확인이요~
