### ISSUE TITLE
Help(채팅 리액션)

### ISSUE THREAD

**Issue by ryankimjh00** [Team-Discipline/Xlack-Frontend#119]
- 현재 상황
- 리액션을 저장하는 Redux 존재
- 리액션 웹소켓 구조는 {mode: bool, icon: string, chat_id: number}
- 위의 구조로 완벽히 저장되어 어디서든 불러올수 있는 상태
- 하지만 지금 문제점은 이걸 저장할 때 chat_id 별로 저장이 되긴 하지만 하나의 값이라 전역적으로 하나의 리액션만 저장이 되는 상태
- 의문: 그럼 컨테이너를 챗 개수만큼 만들어야 하는가? > map을 사용하여 chat_id를 key로 사용해서 매핑을 하면 가능할지도 모름
- 근데 이렇게 한다 해도 그 모든 리액션을 각각 챗 아이디에 맞게 붙이는 것이 가능할까?

**Comment by ds1sqe** [comment]
1. Reaction websocket에 mode :  boolean 이 왜 있는거지?
2. 저장을 chat object에 reactions ?: Reactions[] 식으로 하면 되잖아 어떤거가 문제라는건지 잘 모르겠어

**Comment by ds1sqe** [comment]
그리고 애초에 첨에 챗 불러올때 이미 이런 형태로 받아올꺼고

**Comment by ds1sqe** [comment]
첨에 백엔드에서 같이 보내줄꺼니까
 
그리고 웹소켓으로는 수정사항 발생할때 브로드캐스트 해줄꺼고

**Comment by ds1sqe** [comment]
정확히 어떤걸 못하겠다는거야?

**Comment by ds1sqe** [comment]
하나의 값만 전역적으로 저장된다는거랑

**Comment by ds1sqe** [comment]
컨테이너가 무슨말인지 모르겠네

**Comment by ds1sqe** [comment]
1. Reaction websocket에 mode :  boolean 이 왜 있는거지?
- 1. 모드를 왜 저장하지?
- 2. 요청할때 모드는 string 임 불런이 아니라. 요청 형태는 내가 pr 올렸던거 확인해봐
2. 저장을 chat object에 reactions ?: Reactions[] 식으로 하면 되잖아 어떤거가 문제라는건지 잘 모르겠어
3. 하나의 값만 전역적으로 저장된다는거랑 컨테이너개수를 챗 개수만큼 생성한다는거가 무슨말인지 모르겠네

벡엔드에선 처음에 챗 불러올때 포함된 관계로 보내주기때문에 그대로 받아올꺼고
웹소켓으로 
- 1. 유저로부터 수정사항 요청처리
- 2. 수정사항 발생할때 브로드캐스트
해줄건데

웹소켓으로 리슨하고 있다가 서버에서 변경사항 알려주면
리듀서로 데이터 조작하면 되지 않을까?

해당하는 chat 찾아서 리액션 프로퍼티 조작하는 형태로

예시 이따가 첨부할께

**Comment by ryankimjh00** [comment]
음 그러네 mode는 create or delete네 확인

**Comment by kreimben** [comment]
https://youtu.be/toRBverVG6k
