### ISSUE TITLE
채팅 모델 변경사항 안내

### ISSUE THREAD

**Issue by kreimben** [Team-Discipline/Xlack-Frontend#124]
백엔드 채팅에서 시간 format 변경 요청에 따라 변경됨을 안내.

## rest api

![Image](https://github.com/Team-Discipline/Xlack-Frontend/assets/20333172/93fd207d-54a4-4a75-9b36-b58cdf1c77cd)

다른 부분은 전부 동일하나 `converted_created_at`라는 필드 추가해줌.
수정된 포맷을 사용하고 싶다면 `converted_created_at`를 사용할것. @ss35789 

## websocket

![Image](https://github.com/Team-Discipline/Xlack-Frontend/assets/20333172/16686c60-ec66-4b48-9872-d125a551ceb6)

기존에 채팅을 치고 응답을 받을때 채팅 친 시간이 표시되지 않았음. 이 부분 요청한 포맷으로 client에게 전달하도록 수정함.

**Comment by ss35789** [comment]
수정함
