### ISSUE TITLE
user_check 실패 

### ISSUE THREAD

**Issue by ss35789** [Team-Discipline/Xlack-Frontend#26]
github에서 유저 정보는 받아오는데 
{"success":true,"message":"Successfully get user information from github."

user_check가 안됨
{"success":false,"message":"User doesn't exists. You have to register."}

user_check 콘솔 메세지
GET https://xlack.kreimben.com/api/authentication/user_check?github_id=55543713 404 (Not Found)

@kreimben @ryankimjh00

**Comment by kreimben** [comment]
@ss35789 @ryankimjh00 

`GET /authentication/user_check`는 github로부터 받은 id를 이용해 해당 깃헙 유저가 우리 서버에 "회원가입이 됐는지" 체크하는 엔드포인트 입니다.

따라서 false가 뜬다면 `User doesn't exists. You have to register.`의 말대로 `POST /user/`를 이용해 회원가입을 해야한다는 소리입니다.

**Comment by kreimben** [comment]
@ss35789 

https://github.com/Team-Discipline/Xlack-Frontend/blob/main/src/features/login.ts

https://github.com/Team-Discipline/Xlack-Frontend/blob/main/src/components/Login.tsx

이미 해당 부분 구현이 돼었으니 확인해 보도록.

**Comment by ss35789** [comment]
06289e6f0d8cfc3edeab320d8a1bd722bca3868e

**Comment by kreimben** [comment]
@ss35789 

https://github.com/Team-Discipline/Xlack-Frontend/commit/4ac15a94c36918a2e6421154ebb5e33808a80fc8

해당 부분 커밋에 적용 시킴.

백엔드 쪽에 저번에 모든 데이터베이스 삭제해서 회원가입하려고 해도 `해당권한이 없습니다.`라고 떴던게 이유...
백엔드 잘못이네... Sorry.
