### ISSUE TITLE
일부 워크스페이스 내부의 Channel의 ContextMenu가 사라지지 않는 버그 존재

### ISSUE THREAD

**Issue by ss35789** [Team-Discipline/Xlack-Frontend#95]
일부 워크스페이스 내부 채널의 우클릭 메뉴가 다른 곳을 클릭 해도 닫히지 않는 버그 수정해야 함,
다른 워크스페이스로 바꿧다가 돌아오면 사라짐

**Comment by kreimben** [comment]
해당 기능구현한 이슈로 가서 댓글 달기 바람.
