### ISSUE TITLE
[f] FE Login Issue

### ISSUE THREAD

**Issue by ryankimjh00** [Team-Discipline/Xlack-Frontend#97]
1. cookie에 ac가 전달이 안될 가능성.
2. ac가 저장이 안됐을 가능성.
3. Login.tsx:49 에서 if(access_token)이 작동 안되는것을 확인(ac가 undefined. rc either)
4. 정한이형 컴퓨터에서 특수하게 LoginDjango 메서드가 작동하지 않는것을 확인
5. LoginDjango가 작동하는 것을 확인 (token_info log 추적)
5. cookie.ts:27 에서 setCookie가 작동하지 않는 것을 확인
![image](https://user-images.githubusercontent.com/85392646/220125237-fe8aa841-2db6-44c1-8f58-d14e24bbdb89.png)

**추가적으로 의심가는 부분 추가 바람**

**Comment by kreimben** [comment]
Solved.
